#!/usr/bin/env ruby
# frozen_string_literal: true

EXECUTABLE = "cursor"

HOME = `echo $HOME`.strip
PATH = File.join(HOME, "/Library/Application Support/Cursor/User/extensions")

unless `which #{EXECUTABLE}`.empty?
  cursor_extensions = `cat "#{PATH}"`.lines.sort
  installed_extensions = `#{EXECUTABLE} --list-extensions`.lines.sort
  uninstalled_extensions = cursor_extensions - installed_extensions

  print "Checking for uninstalled Cursor extensions..."

  if uninstalled_extensions.empty?
    puts "All extensions are installed"
  else
    puts "Found #{uninstalled_extensions.count} uninstalled extensions"

    uninstalled_extensions.each do |extension|
      puts "Installing #{extension}..."
      `#{EXECUTABLE} --install-extension #{extension}`
    end

    puts "Done!"
  end
end
