[".config/tmux/tmux.conf"]
	type = "file"
	url = "https://raw.githubusercontent.com/gpakosz/.tmux/master/.tmux.conf"
	refreshPeriod = "168h"

[".oh-my-zsh/custom/themes/powerlevel10k"]
	type = "archive"
	url = "https://github.com/romkatv/powerlevel10k/archive/v1.20.0.tar.gz"
	stripComponents = 1
	exact = true
